apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  destination:
    name: ''
    namespace: sealed-secrets
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    targetRevision: 2.5.2
    chart: sealed-secrets
  project: default
  syncPolicy:
  syncOptions:
    - CreateNamespace=true
    - PruneLast=true

