apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-basic-auth
  namespace: monitoring
spec:
  encryptedData:
    auth: AgCdPnlhEhmUA6iwYZdPiw2tiVicTpaMCkSNvpRCSuhNk3T2vZVbPGcgP3J1vrJC51j+7H5z5CaiHRrW6Xs9ppw2axYtSjZ+UZ//FxSaJssM0pZR1PAfG49nsE/qQHnFcLRaXMOBo77JHglZc4qOh3HzbAVT/GyJGzaAkA5pn/5dyZZVdAGSbc1TGc1HiLwrTIgEvJAm11SZQd+dinwErUsNiKTS1NTwWa4pJvGPUdwIbcgZc3Z1AVVVDHzUd3K9P0EpERpm14zp8Xm7grZl/H0PLPqxHC75M6rpSXSjo7jQ3ZVLyScRGN8lK5kl8+CZgo06S7qZt2t9AoSq0d57l9Owm87pwUDVqKsaEtMt8FQ5hvtONFP2YVDIiJhp5flv0uuap6CVTLa7h7n7ggZsfKhG8S3lZjm1UWfS8/nVRd28DdTJ10I5IA6cBsuBWzRiume3CPdT6YUIbexyXsoUxALRDTAJH/ewjFwfWC8K1xGsJuNKZDo9NJ2DMSllX2ikotiv/R4IxBEDnw+/7bUOxz9hPhmjQU9vLjnUhmGVHtqibvfPBd23eaisr7vSMoObGaToJ0rnYleDSX9FDj8ATWY8daV2GguqBxbloGpGfj7zcKBwWg36KYzi5s5xyiHIfyQdNrXnPTTTgWAQuvxoH+cDhjZtEziHqwpTlkMcq63iX3mFhB9h90RAsYCyuruiBM96V8klQ49CFjEKVBocqxGOX+CXfxIpa2MdKaBf5lCWmAq1gtD+jXYHw7J1J+5RA0n4TA==
  template:
    metadata:
      creationTimestamp: null
      name: monitoring-basic-auth
      namespace: monitoring
    type: Opaque

