apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  destination:
    name: ''
    namespace: ingress-nginx
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/manifests/ingress
    repoURL: 'https://github.com/simpledotorg/container-deployment.git'
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  destination:
    name: ''
    namespace: sealed-secrets
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/manifests/sealed-secrets
    repoURL: 'https://github.com/simpledotorg/container-deployment.git'
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/manifests/argocd
    repoURL: 'https://github.com/simpledotorg/container-deployment.git'
    targetRevision: master
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  destination:
    name: ''
    namespace: grafana
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/manifests/grafana
    repoURL: 'https://github.com/simpledotorg/container-deployment.git'
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true

---

kind: Application
metadata:
  name: secrets
spec:
  destination:
    name: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/argocd-apps/bd-k3s-demo/secrets
    repoURL: 'https://github.com/simpledotorg/container-deployment.git'
    targetRevision: master
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
