apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simple-server
    spec:
      containers:
      - name: simple-server
        image: {{ .Values.image }}
        command: ["bin/rails", "server",  "-b", "0.0.0.0"]
        envFrom:
          - secretRef:
              name: {{ .Values.secret_name }}
      initContainers:
        - name: init-db
          image: {{ .Values.image }}
          command: ["/bin/bash"]
          args: ["/opt/app/script/k8s_db_setup.sh"]
          envFrom:
            - secretRef:
                name: {{ .Values.secret_name }}
