apiVersion: v1
kind: Service
metadata:
  name: simple-server
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/name: simple-server
  sessionAffinity: None
  type: ClusterIP
