metabase:
  image:
    tag: v0.47.10
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: simples9.health.gov.lk
        paths:
          - path: /
            pathType: ImplementationSpecific
      - host: metabase-simple.health.gov.lk
        paths:
          - path: /
            pathType: ImplementationSpecific
