apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: argocd
spec:
  encryptedData:
    auth: AgABF+knAAm7hv/txLRa42N+5aAT+a93sRN5Gozu3cQ+lf2X+o9L+TzR7uhemKWk3CDTtHGIyjB8YqLpIvSKhV5TcDHFS4jKM/2parsSB3fnJ9Jtsp30JhvKT8q7tTKpwWxOoQM5Nxa+YsjA/au3i2C1ijz0Zo6l7rc+yRVE89M9vKBjKC2ozyFzPzasrm4m1FmmAQp2tPZfCnL+M1aI/nKi4m099yol5aQJD6/erKNruhBXS5o4v6UHtwufrCrbb3ZZ7kgTvGfPPjAi8Efs6NK/XnKwVH2YkF9NNXu4JdCNNU5laCEzDz5JteXwlbUr1VMOsiIiTFQhTNX0oIztCJ0BAdmBDiegduI+aKRlTHk+7dMZzHubcNCz7gWfGL98q26FBfJZgeAKuV/kg3J6LO2UEvu4AjPEF8gW2VazpyZO3SYscMXrZF6b/HwaM0z60/Ps3cvDrO7ZatF13MetB9fD7nN0z0qHYXakLxYcoVx9IOrQezFHI9kImTzIXlL58iG8KxpfB5MjYGeAUbYOMqZCxy7/vIG21siJla9bVPvzDyL40v0bD2Lb0vsksYq//j9sePEvBS9EZLCoB9H/8GfZ4FZefEIwO+aW/izdDbac9PPAgbrGaCeYu0ogr0yJ43hL0IBKNDJqhViIqzZL5jNRFX3jkHwnUmRhJpm+SafDs9LuwkRsv4EYRBLYrz1Dn7Q2OHitbfHIzuh/ftsTCswnoXy50MFr1fgn9oHK9Yo7niPWMEGfzh0y8Pr9nQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: argocd
