apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: argocd
spec:
  encryptedData:
    auth: AgAV4KugcxIXCtNh3BF/fb/KZSYYZJntCjHnB7tfkkbktRIO3fJbLHJrSsYJFHFXPMa58/XnqijwYlbTWmFPfKFwRmj8Ffz24aGyNQ0KTlWAuFTrlQSBTWhDo+2KG/3Klp42UbLiztSO/Auq71FcjbIlY6saDi32SHxAUPatQhnGGJ2vnHJhZGnEc/NcpmazXK5sUrdBaaOfXFP0bUmjzceSOAzBk+xDJft9u1q9k1wq0UP43bGbSGqH/8To35kABf9ISn8DFzJXa+Uu4ve2ObsD1tUssmmc3YbKZyrN7dG5ds2uH3U/HMMB4Vhidx8FSKKu5mpr1BghPnGQjwG0PfiRWG+MolhdqL0OJQWxg8DKalQX4IfpZaZkNOQkjmz6o4Mp/vq7iweKQLK9aDbO2wemhXg96Vjr4BgbrPE4ILdcFz7ExBfmZP1OOTHh4MtsMgyYghYieNZU7WXDHt1PlirgBZR+e3Gp6jzvcS5PwxVEex42Xe6kkBPphzM6Mw8pOyRxEKVzbsAAfAiWPeJvT1HVEccGiEJJiz8UzZMI55CxYnmpEfhwW83jaUoAYfdyZcq9w5j/4koBWydrnfT8iJ93JpLUp6yyYckKI6i8dCnxgN2pahBKtxcIkTe/0AivQY5dT27Wkrh01LGQjp7TBpyYzS9JugI8TRg94uCGUX5IiTV0WC4mKXebdFGnY+ExaMOlUtMEric18TjqvuBR3Xv4105NbN3bzq6LCma/798gwGBhvuUCDkLUQwzEQw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: argocd
