apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: simple-server-pg
  namespace: simple-v1
spec:
  encryptedData:
    postgresql-password: AgBLn/Qco8an2X8p7J5K+mzulD8IWE5TlelxwyqTdkMLXiIRFKjuCf2P6g9IC6chGFaujMy43Zv/wfIS8x5/mFNR3HuzQpEdR/uAfpKvJCTqHZt6wbaJp/J7ltNn/mKQwaGRDHmdwikL5ltywASC4iKgcnBe5uGH4Xo8JfwOnz/59pqFP4H/qhpnmwoPbu62DzIYrsYvW7NQszdcJAFkBCEwjm0jHFptudvacb0uhLYtLQZCzseYJeyYVpMIsYaFE4m3WcbV+aeIrf9Q2fu+xdKf2O2he+/4qUl3X4ZcNnKTRlyZoUBXASiqCkohLxvmWsqpWzoKCYUki9QTxE2l4UvS0CKQI0Pxibj1/fREEyfAUrd8gVfWfMBj/Vq/lEc+z3Yy56rfkcdGqL60A7iUHilmNf/MIobinaZV8rpHD8tNL6c8yPcYm2MSLQmwYcEQuq6IiFT0ZTWEcw+yXDouWyQp4SJ/CoOusGBqBakWnrWhpKKI0XiyTxjJ/H/lZ7iz6EvYrDg0zPgewUyYJ9W+CCuLxUgwpVSVyvAOGAJxFC+y8/WqSUffL1wRgDln6YoopIOKZH55E+QLg5hZCGMGjDJN3UjwpGQw/x35NLDCVy/KVyZAp+l+f/s01mwVFeImFRS/F6LsBP8WQqh+x+8eiz/JFlN5p5L3AxMKwQz9WTcWmCqwTQ+YnLykciRsWL1BlJ8ifXCpJ4PiTm44PoY=
    repmgr-password: AgANWxAWENnp6d69x4l0o8utxcNmiYptvUU4ApxOFtUyOR3sNhlDnYlEhl0gHU05E4yNSLlRp/waoRVv3DfnMTMmIx9GszaRG4lJmqG4fc22juaVqyvSmZ8vqXdABmcbrOMto9sKpBvaK4ItHiOLtX19gjvgYxsbgsnTHf2lmfCQuoCf/xscwRHpdA3u7gPO61C40bsVU5hFIz5CCmBFJQlABa/NxR6t2QEjtGzV5K2h/JMTsqCu4XLeonrnv0G40g+QlN+AzdPa0XCg+4bdAC509DeOxUDd4s2c2kUxPOGg1iNX4Ecx/PkJFAbREZW/MWn3wTYKeolt1XOkx+y6FQxO15MqI9HVyiyqFcqeQPcxeDnLJJIjwAH9SLA77l1MpkB07Qm517SapfFMr9TTEQr+z2xRjQv3e9BC9FuTmYJPPA0IFw1GslIf6EIUbE/O5sl7BlTFRBDebgfPjA6X5j363PF1HaxbXDKuSo5joT3JYwlLUgINLjc7xEV0tuCUQyJBXRkyMyMzb2g1pgsp+cRkQxS0KL4jZA5qTq3U5nIzKcbHbTEzA50aqr1CcVWjFcdDFZEnNnwRYgoJFqnBfE4zhJgphVVIBvy0HLerjJeg2YvG7Y5yUxurHMi2CFVnM0ypJ3beeNl8HaQ3N+wnVsYgZ5XBWmxEFFfIEiZeivMXmjNN5c3ve9XlqzshuMTN58EW+cwOJy0BmtV0t/E=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: simple-server-pg
      namespace: simple-v1
    type: Opaque
