prometheus:
  extraScrapeConfigs: |
    - job_name: 'federate'
      scheme: https
      scrape_interval: 15s
      honor_labels: true
      metrics_path: '/federate'
      params:
        'match[]':
          - '{__name__=~".+"}'
      static_configs:
        - targets:
          - 'prometheus-sandbox.simple.org'
      basic_auth:
        username: 'db25a3474d90'
        password_file: '/etc/secrets/default'
  server:
    persistentVolume:
      size: 100Gi
    extraSecretMounts:
      - name: secret-files
        mountPath: /etc/secrets
        subPath: ""
        secretName: prometheus-auth
        readOnly: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
        nginx.ingress.kubernetes.io/auth-secret: monitoring-basic-auth
      hosts:
        - prometheus.simple.org
      tls:
        - secretName: prometheus.simple.org-tls
          hosts:
            - prometheus.simple.org
  alertmanager:
    ingress:
      className: nginx
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
        nginx.ingress.kubernetes.io/auth-secret: monitoring-basic-auth
      hosts:
        - host: alertmanager.simple.org
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: alertmanager.simple.org-tls
          hosts:
            - alertmanager.simple.org
    extraArgs:
      web.external-url: "https://alertmanager.simple.org"
      web.route-prefix: "/"
grafana:
  admin:
    existingSecret: "grafana-secrets"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - grafana.simple.org
    tls:
      - secretName: grafana.simple.org-tls
        hosts:
          - grafana.simple.org
  persistence:
    enabled: true
    size: 50Gi
  grafana.ini:
    auth.saml:
      enabled: true
      auto_login: false
      private_key_path: "/etc/secrets/private_key.pem"
      certificate_path: "/etc/secrets/certificate.cert"
      idp_metadata_url: "https://sso.simple.org"
      assertion_attribute_name: DisplayName
      assertion_attribute_login: Login
      assertion_attribute_email: Email
      assertion_attribute_groups: Group
  extraSecretMounts:
    - name: grafana-auth-saml
      mountPath: /etc/secrets
      secretName: grafana-auth-saml
      readOnly: true
