apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  destination:
    name: ''
    namespace: ingress-nginx
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.2.0
    chart: ingress-nginx
    helm:
      parameters:
        - name: controller.hostNetwork
          value: 'true'
        - name: controller.ingressClassResource.default
          value: 'true'
        - name: controller.kind
          value: DaemonSet
        - name: controller.service.type
          value: ''
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
