ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: dhis2-c61c699a.simple.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
  - hosts:
    - dhis2-c61c699a.simple.org
    secretName: dhis2-c61c699a.simple.org-tls
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: dhis2-c61c699a
          operator: In
          values:
          - "true"
