apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
spec:
  destination:
    name: ''
    namespace: simple-v1
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 17.0.7
    chart: redis
    helm:
      parameters:
        - name: auth.enabled
          value: 'false'
        - name: replica.replicaCount
          value: '0'
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
spec:
  destination:
    name: ''
    namespace: simple-v1
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 9.2.7
    chart: postgresql-ha
  project: default
  syncPolicy:
    syncOptions:
      - Replace=true
      - CreateNamespace=true
      - PruneLast=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple
spec:
  destination:
    name: ''
    namespace: simple-v1
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s-manifests/simple/manifests
    repoURL: 'https://github.com/simpledotorg/container-deployment.git'
    targetRevision: master
  project: default
  syncPolicy:
    syncOptions:
      - Replace=true
      - CreateNamespace=true
