apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  destination:
    name: ''
    namespace: grafana
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 8.0.7
    chart: grafana
  project: default
  syncPolicy:
  syncOptions:
    - CreateNamespace=true
    - PruneLast=true
