apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bd-k3s-demo-secrets
spec:
  destination:
    name: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s-manifests/secrets/bd-k3s-demo/manifests
    repoURL: 'https://github.com/simpledotorg/container-deployment.git'
    targetRevision: master
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
