ingress:
  enabled: true
  className: "nginx"
  annotations:
    "cert-manager.io/cluster-issuer": "letsencrypt-prod"
    "nginx.ingress.kubernetes.io/auth-type": "basic"
    "nginx.ingress.kubernetes.io/auth-secret": "basic-auth"
    "nginx.ingress.kubernetes.io/auth-realm": "Authentication Required"
  hosts:
    - host: api.k8s-test.simple.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
  - hosts:
    - api.k8s-test.simple.org
    secretName: api.k8s-test.simple.org-tls
