apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-main
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgAM/qaCyulShlWDqDlJjlA9G0HMd6/TnnE2TgogdcCVmYmQK87MqnfoE8lDC6DuDDqxMUso1nWxjV3xzPfom+IykKvUW6WlE15iUBcULb+XnbO/o4UqtAo1eUtTA2QoV/5mJ4L/WObHiWG/rbku7qwLHRgBXSHjSrBNqQFPx0UHnKrfp0Sl1vCHDMtK1fszO1A1h/BqO1K6aT+08yOtUE+pLS0McsjtiguOtUvI9NTEtfN3BHzcLDPqg9TtCKNyxrxgzy54k4G5QAMb1/jjP6BDTrQiGCyPPuBrt9jh5bYexPqXe039HEQLG5Upl3YTgKZbXG7bRVHPv+Xp/ZLZRPoIgVKEYCqpWil5W1CTAM16dPF/Q8tNhcl9jsiZVKczYR6EQ0AT3Kxf4yH7Nii+R0aqfcv5Iw2DmnpuF1dtoTnnYPR1du95cZhOdW3u6djByNhZUTu3MNyz1kV9P4XLbbHTUJL3ylK057e/VZk7F9gMeTUbEr7aSG86ImZIA3/ABkAAiXG9+u8kXzUFiwBZ5VK353f1w+sJ1V+OC1ssfbngbliSOjRXyLrHd0t6oxnAZinkjjgU81j8J5weHfnsGnjRd6w6yT+y63hvaKWF/zArNi0WcqYzc9in0Dh2dA91asj4fb69wc4IMGzDsUEoau7b3+hL2NshUb2QNMs2ifeVCNDohk2nWvh7Vo0RZtJ9KgZMtj847XYWg5cm7CCb4LNoG5q15xASouM2jFT3QA==
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-main
      namespace: monitoring
    type: Opaque

