apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-main
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yml: AgBQsUZU66z32dyFKvEUMB1Gwyu3fl5C1Ntrze3bvtEkUgEMPLxqmDuPuRZ2r2QsrV/lVaz82vgpFZgMK2yv35P0jmeEZI1bzx3MrtovhEuXNShskqm5U35mHRoI496nzI96GelSEuWOxjezy0+/Msnb9JVWw05KIAY0o/t3AfGkG+6Udon4u9pzy4RggVS/1uxDwA1njc9KAJ6M1daA+hsfMIo5iro55bEgbxwgqSXh9RopxqoYU4wumF5KKs0A8BDNygs1c2MLblk9/8wGR2axaQWSTQvbUYtP6YzC1dyjTsO5v4QfZUg7TCKLjN2BuM/fqBwdtrFDmkCPVa0FT3AgcK/1UVe2Sy6tRACqaQIX6NTzbqtl78gIvugma//RKBxFFYgCNlW5Wl/st/2H03x1NfMGJitDHO/gXEA84IW/hygEB/7Lu0YBWLM9BzJtkxbXeeS8aU1uNLVLziMKxfJJAgR5Hmu9CmCTRrx37NlVaZcgavUKQM6+yytGXmUNvXBD3EHSirTYiDKnM+39Zi1CeNFHvK9YniBOKzi1KKA0KIrlQkkhcOJ36+dgccXAtdqVy6tIiYVry7PA629UVPh3rO5/vF7C2aFLx/8OH9/IrH8gnmQZ0uDTlKkv7BrRk827i7JUuXqgSaTAwV4CubCLjoHoJgIZ4atHYNMCKZraHeQ0xpgiaa2+k8E8cyzjyqhvwAfqB2aJ57E2EljXa/CBTkmsWuB/qpMgZ/CnUg==
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-main
      namespace: monitoring
    type: Opaque

